In [13]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(np.__version__)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1.18.5
3


In [25]:
import numpy as np
a = np.array([8 ,3, 4])
b = np.array([8 ,1, 5])
print("Original numbers:")
print(a)
print(b)
print("Comparison - greater")
print(np.greater(a, b))
print("Comparison - greater_equal")
print(np.greater_equal(a, b))
print("Comparison - less")
print(np.less(a, b))
print("Comparison - less_equal")
print(np.less_equal(a, b))

Original numbers:
[8 3 4]
[8 1 5]
Comparison - greater
[False  True False]
Comparison - greater_equal
[ True  True False]
Comparison - less
[False False  True]
Comparison - less_equal
[ True False  True]


In [26]:
import numpy as np
arr = np.arange(30,71,2)
print("Ever Integers between 30 to 70")
print(arr)

Ever Integers between 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [20]:
import numpy as np
x = np.identity(3)
print('3x3 Identity Matrix:')
print(x)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
import numpy as np
x=np.arange(0,21)
print("Original is:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x>=9) & (x<=15)] *= -1
print(x)

Original is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [31]:
import numpy as py
arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [35]:
arr = np.array([[5, 8],[3, 6]])
print(arr)
print("Sum of all elements:")
print(np.sum(arr))
print("Sum of the rows:")
print(np.sum(arr, axis=1))
print("Sum of the columns:")
print(np.sum(arr, axis=0))

[[5 8]
 [3 6]]
Sum of all elements:
22
Sum of the rows:
[13  9]
Sum of the columns:
[ 8 14]


In [2]:
import numpy as np
arr1 = np.array([[5, 8],[3, 6]])
arr2 = np.array([[4, 2],[1, 7]])
print("First Matrix:")
print(arr1)
print("Second Matrix:")
print(arr2)
print("Multiplying the first and second matrix:")
print(np.multiply(arr1,arr2))

First Matrix:
[[5 8]
 [3 6]]
Second Matrix:
[[4 2]
 [1 7]]
Multiplying the first and second matrix:
[[20 16]
 [ 3 42]]


In [3]:
import numpy as np
arr = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(arr)
print("\nNew array after swapping first and last rows of the said array:")
arr[[0,-1],:]=arr[[-1,0],:]
print(arr)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [4]:
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))



Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


In [5]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original arr:")
print(x)
header = 'col1 col2 col3'
np.savetxt('test.txt', x, fmt="%d", header=header) 
print("Content of the text file after loading:")
res = np.loadtxt('test.txt')
print(res)

Original arr:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Content of the text file after loading:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
