In [1]:
import numpy as np

In [19]:
n1=int(input("Enter no of row matrix 1:"))
m1=int(input("Enter no of col matrix 1:"))
n2=int(input("Enter no of row matrix 2:"))
m2=int(input("Enter no of col matrix 2:"))

Enter no of row matrix 1: 2
Enter no of col matrix 1: 2
Enter no of row matrix 2: 2
Enter no of col matrix 2: 2


In [20]:
print("Enter elements of Matrix 1")
A=[int(input()) for i in range(0,m1*n1)]
A=np.array(A)
A.resize(n1,m1)

Enter elements of Matrix 1


 1
 2
 3
 4


In [21]:
print("Enter elements of Matrix 2")
B=[int(input()) for i in range(0,m2*n2)]
B=np.array(B)
B.resize(n2,m2)

Enter elements of Matrix 2


 1
 2
 3
 4


In [23]:
#q1
print(np.dot(A,B))


[[ 7 10]
 [15 22]]


In [25]:
#q2
print("Transpose of A")
print(A.transpose())

print("Transpose of B")
print(B.transpose())

Transpose of A
[[1 3]
 [2 4]]
Transpose of B
[[1 3]
 [2 4]]


In [27]:
#q3
print("Trace of A")
print(A.trace())

print("Trace of B")
print(B.trace())

Trace of A
5
Trace of B
5


In [29]:
#q4
print("Rank of A")
print(np.linalg.matrix_rank(A))

print("Rank of B")
print(np.linalg.matrix_rank(B))

Trace of A
2
Trace of B
2


In [30]:
#q5
print("Determinant of A")
print(np.linalg.det(A))

print("Determinant of B")
print(np.linalg.det(B))

Determinant of A
-2.0000000000000004
Determinant of B
-2.0000000000000004


In [33]:
#q6
print("Inverse of A")
print(np.linalg.inv(A))

print("Inverse of B")
print(np.linalg.inv(B))

Inverse of A
[[-2.   1. ]
 [ 1.5 -0.5]]
Inverse of B
[[-2.   1. ]
 [ 1.5 -0.5]]


In [39]:
#q7
print("Eigenvalues of A")
print(np.linalg.eig(A)[0])
print("Eigenvvector of A")
print(np.linalg.eig(A)[1])
print("-"*20)
print("Eigenvalues of B")
print(np.linalg.eig(B)[0])
print("Eigenvvector of B")
print(np.linalg.eig(B)[1])

Eigenvalues of A
[-0.37228132  5.37228132]
Eigenvvector of A
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
--------------------
Eigenvalues of B
[-0.37228132  5.37228132]
Eigenvvector of B
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
